# This file is automatically generated. Do not edit.

if Object.const_defined?('TestFlight') and !UIDevice.currentDevice.model.include?('Simulator')
  NSNotificationCenter.defaultCenter.addObserverForName(UIApplicationDidBecomeActiveNotification, object:nil, queue:nil, usingBlock:lambda do |notification|
  TestFlight.takeOff('e66b41f13e73851791644ec30232d4e0_MTA4NjYzMjAxMi0wNy0xMCAxMTo1NDo1Ny40MjcxODY')
  end)
end
